### ISSUE TITLE
node smart-home-provider-cloud.js isLocal ?

### ISSUE THREAD

**Issue by sunjunlishi** [actions-on-google/actionssdk-smart-home-nodejs#9]
node smart-home-provider-cloud.js isLocal
/home/sun/down/actionssdk-smart-home-nodejs-master/smart-home-provider/cloud/smart-home-provider-cloud.js:55
  let authToken = authProvider.getAccessToken(request);
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by mwidlok** [comment]
try upgrading your node.js to latest version eg: 6.11.0

**Comment by sunjunlishi** [comment]
'use strict'; i hsve resolved it

**Comment by Canain** [comment]
We recommend using the latest (supported for your platform) Node.js version to allow for using ES6 functionality.

**Comment by sunjunlishi** [comment]
'using the latest ' thanks
